<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="..\Constia.Application\Constia.Application.csproj" />
    <ProjectReference Include="..\Constia.Infrastructure\Constia.Infrastructure.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>9fe6d3c8-97b2-4f03-b5ff-b92a9056ae72</UserSecretsId>
  </PropertyGroup>

</Project>
